export const Data = [
    {
        question: 'Tarjoaako rokote pysyvän suojan COVID-19 vastaan?',
        answer: 'Koska COVID-rokotteet ovat tulleet käyttöön vasta viime kuukausina, on liian aikaista arvioida luotettavasti COVID-19-rokotteiden suojan pitkäaikaista kestoa. Tätä tutkitaan tällä hetkellä.<br><br> On kuitenkin rohkaisevaa, että käytettävissä olevat tiedot viittaavat siihen, että nyt COVID-19:stä toipuville ihmisille kehittyy immuunivaste, joka tarjoaa ainakin jonkin verran suojaa uudelleeninfektioita vastaan. [6]'
    },
    {
        question: 'Koronarokote kehitettiin nopeasti – onko tämä merkki siitä, ettei turvallisuusmääräyksiä ja lakia noudatettu?',
        answer: 'Koronarokotteiden kehityksessä on noudatettu samoja laillisia määräyksiä kuin kaikkien muidenkin lääkkeiden ja rokotteiden kehityksessä. Näin voidaan taata koronarokotteen turvallisuus, laatu ja tehokkuus. Koronarokotteiden markkinoille tuloa on myös nopeuttanut poikkeuksellisen suuret resurssit, mikä on osaltaan mahdollistanut useiden tutkimusvaiheiden tekemisen rinnakkain. Lisäksi jo aiemmin tehty laaja tutkimustyö samankaltaisten rokotteiden parissa on nopeuttanut rokotteen valmistumista.</br><br>Kuten kaikki lääkkeet, COVID-19-rokotteiden vaikutukset testataan ensin laboratoriossa, myös eläimillä, ja sitten rokotteet testataan vapaaehtoisilla ihmisillä.[1]<br><br>  Lisätietoa:<br> <a target= "_blank" href= " https://www.ema.europa.eu/en/human-regulatory/overview/public-health-threats/coronavirus-disease-covid-19/treatments-vaccines/vaccines-covid-19/covid-19-vaccines-development-evaluation-approval-monitoring"> COVID-19 vaccines: development, evaluation, approval and monitoring </a>'
    },
    {
        question: 'Olen sairastanut koronan, tarvitsenko enää rokotetta?',
        answer: 'Vaikka sinulla olisi jo ollut COVID-19, sinun tulisi ottaa rokote, kun sitä sinulle tarjotaan. <br><br> Suoja, jonka saa COVID-19 -tartunnan saamisesta, vaihtelee henkilöittäin. Ei myöskään ole varmuutta siitä, kuinka kauan luonnollinen immuniteetti voi kestää. [6]'
    },
    {
        question: 'Onko koronarokote turvallinen?',
        answer: 'COVID-19-rokotteet ovat turvallisia. Kuten minkään lääkkeen tai rokotteen kohdalla, ei harvinaisten haittavaikutusten mahdollisuutta voida sulkea kokonaan pois. Kaikkien koronavirusrokotteiden turvallisuuden varmistamiseksi on kuitenkin tarkat turvallisuuden ja tehokkuuden kriteerit joita testataan muun muassa kymmenillä tuhansilla vapaaehtoisilla koehenkilöillä, ja niiden avulla on varmistettu että kaikissa myyntiluvan saaneissa rokotteissa hyödyt ovat merkittävästi suurempia mahdollisiin haittoihin verrattuna. Rokotteille, joita ei voida todistaa turvallisiksi, ei siis myönnetä myyntilupaa. <br><br> Suurin osa haittavaikutuksista on lieviä, vaarattomia ja itsestään ohimeneviä. Vakavien haittavaikutusten todennäköisyys on Suomessa ollut haittavaikutusilmoitusten perusteella 0,00045 prosenttia. [8][11]'
    },
    {
        question: 'Onko Astra Zenecan rokotteessa suuri riski veritulppaan?',
        answer: 'Ei ole, tutkimusten mukaan 182 ihmistä sadasta yhdeksästäkymmenestä miljoonasta ovat saaneet veritulpan. <br><br> Jos siis näiden kahden tapahtuman välillä olisi linkki, se olisi erittäin heikko ja epätodennäköinen linkki. Todennäköisyytenä tämä tarkoittaa 0,000095 prosenttia.<br><br>  Esimerkiksi todennäköisyys sille, että salama iskee sinuun elinaikanasi, on 1:15000 eli prosentteina 0,0066. Tämä on huomattavasti suurempi kuin riski saada veritulppa rokotteesta. [9] [10]'
    },
    {
        question: 'Mitä tarkoittaa laumaimmuniteetti?',
        answer: 'Laumaimmuniteetti, joka tunnetaan myös nimellä populaation immuniteetti, on epäsuora suoja tartuntatauteja vastaan. Laumaimmuniteetti muodostuu, kun riittävä osa populaatiosta on immuuni taudinaiheuttajalle joko rokottautumisen tai edellisen infektion kautta syntyneen immuniteetin avulla. [3] <br><br>  Laumaimmuniteetti tarkoittaa käytännössä siis tilaa, jossa tarpeeksi suuri osa populaatiosta on immuuni taudille. COVID-19 tapauksessa noin 70 prosentin rokotuskattavuuden arvellaan riittävän laumaimmuniteettiin. <br><br>  Kun tarpeeksi suuri osa on rokotettuja tai sairastaneita, virus ei leviä enää populaatiossa tehokkaasti ja myös rokottamattomat ovat siltä turvassa laumaimmuniteetin ansiosta. <br><br> Lue lisää:<br> <a target="_blank" href="https://www.who.int/news-room/q-a-detail/herd-immunity-lockdowns-and-covid-19?gclid=CjwKCAjw1uiEBhBzEiwAO9B_Hcab-fPIzH44FvkdRLTJZILJ3f_vR7RabXf27Z2gCKqVEzMVmFS8dxoC3dMQAvD_BwE#"> Coronavirus disease (COVID-19): Herd immunity, lockdowns and COVID-19 </a>'
    },
    {
        question: 'Suojaako rokote, kun virus mutatoituu?',
        answer: 'Virukset tyypillisesti mutatoituvat. Mutaatio tarkoittaa sitä, kun viruksen geneettinen materiaali muuttuu. Mutaatioita tapahtuu eri viruksilla eri nopeuksilla. <br><br>Mutaatiot eivät välttämättä vaikuta siihen, kuinka hyvin rokote toimii virusta vastaan. Tiedeyhteisö ja sääntelyviranomaiset seuraavat tarkasti, kuinka virus muuttuu ajan myötä ja kuinka hyvin rokotteet voivat suojata ihmisiä viruksen muunnosten aiheuttamalta virukselta.<br><br> Joidenkin virussairauksien vastaiset rokotteet ovat tehokkaita vuosien ajan niiden kehittymisen jälkeen ja tarjoavat pitkäaikaisen suojan. Näihin kuuluvat tuhkarokko- ja vihurirokkorokotteet.'
    },
    {
        question: 'Mitä hyötyä nuorille on rokotteen ottamisesta, jos koronavirustartunta ei aiheuta vaaraa terveydelle ja rokotteesta voi tulla haittavaikutuksia?',
        answer: 'Nuoret levittävät eniten koronavirusta, ja vaikka nuori ei itse sairastuisi vakavasti, hän saattaa tartuttaa muita ihmisiä ympärillään. Jos nuorten keskuudessa laumaimmuniteetti jää saavuttamatta, on olemassa riski, että pandemiaa ei saada pysäytettyä, vaan virus mutatoituu ja rokotetun väestön suoja heikkenee ajan kuluessa. Tämä mahdollistaa taas uusien pandemia-aaltojen syntymisen. <br><br> Vaikka rokotteista voi aiheutua haittavaikutuksia, ne ovat todella epätodennäköisiä. Rokotteen ottamisen hyödyt ovat siis selvästi suuremmat kuin haitat. Myös terveet nuoret ovat saaneet pitkittyneitä ja vaikeita oireita koronavirustartunnasta, ja rokote antaa vahvan suojan koronaviruksen aiheuttamia vakavempia tautimuotoja vastaan.<br><br>Vasta, kun riittävä osa myös nuoresta väestöstä on rokotettu, voimme palata normaaliin elämään. Luultavasti normaaliin palaamisen yhteydessä esimerkiksi suuriin yleisötapahtumiin kuten festareille osallistumiseen tai ulkomaille matkustamiseen vaaditaan rokotuspassi, joten kannattaa senkin takia hoitaa rokotus ajallaan kuntoon! [10]'
    },
    { 
        question:'Lähteet:',
        answer: '[1]:<br><br> <a target="_blank" rel="noopener noreferrer" href = "https://www.ema.europa.eu/en/human-regulatory/overview/public-health-threats/coronavirus-disease-covid-19/treatments-vaccines/vaccines-covid-19/covid-19-vaccines-key-facts"> European Medicines Agency: Covid-19 Vaccines: Key Facts</a> <br><br> [2]:<br><br> <a target="_blank" rel="noopener noreferrer" href= "https://www.nbcnewyork.com/news/coronavirus/everything-you-need-to-know-about-the-covid-vaccines-how-effective-are-the-big-3-and-how-do-they-compare/2990057/">NBC New York: Everything to Know About COVID Vaccines </a> <br><br> [3]:<br><br> <a target="_blank" rel="noopener noreferrer" href = "https://www.who.int/news-room/q-a-detail/herd-immunity-lockdowns-and-covid-19?gclid=CjwKCAjw1uiEBhBzEiwAO9B_Hcab-fPIzH44FvkdRLTJZILJ3f_vR7RabXf27Z2gCKqVEzMVmFS8dxoC3dMQAvD_BwE#"> WHO: Coronavirus disease (COVID-19): Herd immunity, lockdowns and COVID-19 </a> <br> <br> [4]: <br> <br> <a target = "_blank" rel="noopener noreferrer" href= "https://www.bbc.com/news/av/health-54937276"> BBC: WHO worried young people wont want vaccine </a> <br> <br> [5]: <br> <br> <a target= "_blank" rel="noopener noreferrer" href= "https://www.who.int/emergencies/diseases/novel-coronavirus-2019/advice-for-public/myth-busters?gclid=CjwKCAjw1uiEBhBzEiwAO9B_HcJgPZonbg4PX4mVzu5GX07mY_05vQz0-4t5pK4IDqOzJ3kbY1k93BoCUSYQAvD_BwE" >WHO: Coronavirus disease (COVID-19) advice for the public: Mythbusters</a> <br> <br>[6]:<br><br> <a target ="_blank" rel="noopener noreferrer" href="https://www.who.int/news-room/q-a-detail/coronavirus-disease-(covid-19)-vaccines?adgroupsurvey={adgroupsurvey}&gclid=CjwKCAjw1uiEBhBzEiwAO9B_HZ7-g9_UsmJS13ehLOovvFXeBwA1jlNjdQDEtQ4ELHfnKy_Hl0_y1RoCe_4QAvD_BwE"> WHO: Coronavirus disease (COVID-19): Vaccines </a> <br> <br> [7]: <br><br> <a target="_blank" rel="noopener noreferrer" href="https://yle.fi/uutiset/3-11298036">YLE: Lepakoita, käärmeitä, ihmisiä ja siipikarjaa vieri vieressä – Koronaviruksen epäilty lähtöpaikka oli riskialtis ruokatori, ja niiden saaminen kuriin on Aasiassa iso urakka</a> <br><br> [8]: <br><br> <a target="_blank" rel="noopener noreferrer" href="https://www.who.int/news-room/feature-stories/detail/side-effects-of-covid-19-vaccines#:~:text=COVID%2D19%20vaccines%20are,body%20is%20building%20protection.">WHO: Side Effects of COVID-19 Vaccines </a> <br> <br> [9]: <br> <br> <a target= "_blank" rel="noopener noreferrer" href="https://www.gavi.org/vaccineswork/what-blood-clotting-disorder-astrazeneca-vaccine-has-been-linked?gclid=CjwKCAjw1uiEBhBzEiwAO9B_HRrJO5SWHFFOvSSMypGhQQEZHqBJpJUqASrZDTP2GPv2Q0HeDwLAyhoC5pUQAvD_BwE"> Gavi: What is the blood clotting disorder the AstraZeneca vaccine has been linked to? </a> <br><br> [10] <br><br> <a target= "_blank" rel="noopener noreferrer" href="https://www.hs.fi/politiikka/art-2000007919771.html">HS: EU:n rokotuspassi tulossa käyttöön kesäkuussa, voimassa kesään 2022: Tarkoituksena on helpottaa matkustamista</a>'

    }
]